### ISSUE TITLE
cannot load from home directory using envkey/envkeygo/v2

### ISSUE THREAD

**Issue by tegaralaga** [envkey/envkey#27]
guys, when I am using envkey/envkeygo/v2, I cannot load the ENVKEY from the home directory env file, even though it is stated that it will look into the home directory https://github.com/envkey/envkeygo/blob/647a3a294c40bea14988a6bf1849829197baf38d/loader/loader.go#L22

it is set to "envFileOverride"
https://github.com/envkey/envkeygo/blob/647a3a294c40bea14988a6bf1849829197baf38d/loader/loader.go#L25

These conditions will never be met

https://github.com/envkey/envkey/blob/923147cdbc8b71696f4d48f2984daae4a74cef0d/public/sdks/envkey-source/env/env.go#L79

or I am wrong in reading the code?

I am sorry for the broken English

**Comment by danenania** [comment]
Should now be fixed in envkey-source 2.027 and envkeygo 2.0.10

**Comment by tegaralaga** [comment]
Hi @danenania I don't see it is fixed.

from https://github.com/envkey/envkeygo/blob/master/loader/loader.go#L25 still using `"envFileOverride"` as an override.
the condition in https://github.com/envkey/envkey/blob/sdkgo-v2.0.10/public/sdks/envkey-source/env/env.go#L75 will never met.

**Comment by danenania** [comment]
I see--missed that there was also a problem in envkeygo. A fix will be out shortly.

**Comment by danenania** [comment]
@tegaralaga should now be fixed in envkeygo 2.0.11

**Comment by sasimovva** [comment]
@danenania - We are still having this issue with envkeygo on 2.3.0..
